# Installs dependencies for YOLACT managed by Anaconda. 
# TODO: you must additionally install nVidia drivers, eg. on linux 
# `apt install nvidia-driver-435`
name: yolact-env
dependencies:
  - python>=3.0
  - pip
  - pytorch >= 1.0.1
  - torchvision
  - cython
  - pip:
    - cython
    - opencv-python 
    - pillow==6.2.1 # bug PILLOW_VERSION in torchvision, must be < 7.0 until torchvision is upgraded
    - pycocotools 
    - matplotlib 
    - PyQt5 # needed on KDE/Qt envs

