# Installs dependencies for YOLACT managed by Anaconda. 
name: yolact-env
dependencies:
  - python>=3.0
  - pip
  - pytorch >= 1.0.1
  - torchvision
  - cython
  - pip:
    - cython
    - opencv-python 
    - pillow==6.2.1 # bug PILLOW_VERSION in torchvision, must be < 7.0 until torchvision is upgraded
    - pycocotools 
    - matplotlib 

